# Generated by Django 6.0.2 on 2026-02-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата найма'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Почасовая ставка'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Базовый'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Эксперт')], default=1, verbose_name='Уровень')),
                ('years_experience', models.FloatField(default=0, verbose_name='Лет опыта')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
