# Generated by Django 6.0.2 on 2026-03-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_user_hire_date_user_hourly_rate_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец обеда'),
        ),
        migrations.AddField(
            model_name='user',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало обеда'),
        ),
    ]
