# Generated by Django 6.0.2 on 2026-02-23 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('technical_spec', models.TextField(blank=True, verbose_name='Техническое задание')),
                ('complexity', models.IntegerField(blank=True, null=True, verbose_name='Сложность (1-10)')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бюджет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('archived', 'Архивный')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало работ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Плановая дата начала')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('planned_start', models.DateField(verbose_name='Плановая дата начала')),
                ('planned_end', models.DateField(verbose_name='Плановая дата окончания')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('delayed', 'Задержка')], default='pending', max_length=20, verbose_name='Статус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_stages', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап дорожной карты',
                'verbose_name_plural': 'Этапы дорожной карты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(blank=True, max_length=100, verbose_name='Роль')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата снятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('planned_hours', models.FloatField(blank=True, null=True, verbose_name='Плановые часы')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение на проект',
                'verbose_name_plural': 'Назначения на проекты',
                'unique_together': {('project', 'user', 'is_active')},
            },
        ),
    ]
