# Generated by Django 6.0.2 on 2026-06-01 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Запланированная дата'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assigned_to'], name='tasks_task_status_d50342_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_date', 'priority'], name='tasks_task_schedul_7fe929_idx'),
        ),
    ]
